// export const ADD_COMMENT = 'ADD_COMMENT';
// export const DISHES_LOADING = 'DISHES_LOADING';
// export const DISHES_FAILED = 'DISHES_FAILED';
// export const ADD_DISHES = 'ADD_DISHES';
// export const ADD_COMMENTS = 'ADD_COMMENTS';
// export const COMMENTS_FAILED = 'COMMENTS_FAILED';
// export const PROMOS_LOADING = 'PROMOS_LOADING';
// export const ADD_PROMOS = 'ADD_PROMOS';
// export const PROMOS_FAILED = 'PROMOS_FAILED';
// export const LEADERS_LOADING = 'LEADERS_LOADING';
// export const ADD_LEADERS = 'ADD_LEADERS';
// export const LEADERS_FAILED = 'LEADERS_FAILED';
export const ADD_USER = 'ADD_USER';
export const USER_LOADING = 'USER_LOADING';
export const USER_FAILED = 'USER_FAILED';
export const USER_PASSWORD_CHANGE_FAILED = 'USER_PASSWORD_CHANGE_FAILED';
export const ADD_ALL_USERS = 'ADD_ALL_USERS';
export const USERS_FAILED = 'USERS_FAILED';
export const USERS_LOADING = 'USERS_LOADING';
export const EDIT_USER_FAILED = 'EDIT_USER_FAILED';
export const REMOVE_USER_FAILED = 'REMOVE_USER_FAILED';

export const ADD_EVENTS = 'ADD_EVENTS';
export const EVENTS_LOADING = 'EVENTS_LOADING';
export const EVENTS_FAILED = 'EVENTS_FAILED';
export const CREATE_EVENT_FAILED = 'CREATE_EVENT_FAILED';
export const EDIT_EVENT_FAILED = 'EDIT_EVENT_FAILED';
export const REMOVE_EVENT_FAILED = 'REMOVE_EVENT_FAILED';

export const ADD_PROJECTS = 'ADD_PROJECTS';
export const PROJECTS_LOADING = 'PROJECTS_LOADING';
export const PROJECTS_FAILED = 'PROJECTS_FAILED';
export const CREATE_PROJECT_FAILED = 'CREATE_PROJECT_FAILED';
export const EDIT_PROJECT_FAILED = 'EDIT_PROJECT_FAILED';
export const REMOVE_PROJECT_FAILED = 'REMOVE_PROJECT_FAILED';

export const ADD_RESOURCES = 'ADD_RESOURCES';
export const RESOURCES_LOADING = 'RESOURCES_LOADING';
export const RESOURCES_FAILED = 'RESOURCES_FAILED';
export const CREATE_RESOURCE_FAILED = 'CREATE_RESOURCE_FAILED';
export const EDIT_RESOURCE_FAILED = 'EDIT_RESOURCE_FAILED';
export const REMOVE_RESOURCE_FAILED = 'REMOVE_RESOURCE_FAILED';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
// export const FAVORITES_LOADING = 'FAVORITES_LOADING';
// export const FAVORITES_FAILED = 'FAVORITES_FAILED';
// export const ADD_FAVORITES = 'ADD_FAVORITES';
