const dumResources = [
  {
    internal_name: 'res',
    directory_year: '2018',
    subdirectory: 'ppts',
    name: 'Attendance.xlxs',
    archive: true,
    description: 'This is the best useful resource so far for the devclub of iit delhi',
    url: 'www.google.docs',
    new: false,
    display_on_website: false,
  },
  {
    internal_name: 'res1',
    directory_year: '2018',
    subdirectory: 'ppts',
    name: 'Attendance.xlxs',
    archive: false,
    description: 'This is the best useful resource so far for the devclub of iit delhi',
    url: 'www.google.docs',
    new: false,
    display_on_website: false,
  },
  {
    internal_name: 'res2',
    directory_year: '2018',
    subdirectory: 'ppts',
    name: 'Attendance.xlxs',
    archive: false,
    description: 'This is the best useful resource so far for the devclub of iit delhi',
    url: 'www.google.docs',
    new: false,
    display_on_website: false,
  },
  {
    internal_name: 'res3',
    directory_year: '2018',
    subdirectory: 'ppts',
    name: 'Attendance.xlxs',
    archive: false,
    description: 'This is the best useful resource so far for the devclub of iit delhi',
    url: 'www.google.docs',
    new: false,
    display_on_website: false,
  },
  {
    internal_name: 'res4',
    directory_year: '2018',
    subdirectory: 'ppts',
    name: 'Attendance.xlxs',
    archive: true,
    description: 'This is the best useful resource so far for the devclub of iit delhi',
    url: 'www.google.docs',
    new: false,
    display_on_website: false,
  },
  {
    internal_name: 'res5',
    directory_year: '2018',
    subdirectory: 'ppts',
    name: 'Attendance.xlxs',
    archive: true,
    description: 'This is the best useful resource so far for the devclub of iit delhi',
    url: 'www.google.docs',
    new: false,
    display_on_website: false,
  },
  {
    internal_name: 'res6',
    directory_year: '2018',
    subdirectory: 'ppts',
    name: 'Attendance.xlxs',
    archive: false,
    description: 'This is the best useful resource so far for the devclub of iit delhi',
    url: 'www.google.docs',
    new: false,
    display_on_website: false,
  },
  {
    internal_name: 'res7',
    directory_year: '2018',
    subdirectory: 'ppts',
    name: 'Attendance.xlxs',
    archive: true,
    description: 'This is the best useful resource so far for the devclub of iit delhi',
    url: 'www.google.docs',
    new: false,
    display_on_website: false,
  },
];

export default dumResources;
