// eslint-disable-next-line import/prefer-default-export
export const dumTasks = [
  {
    id: 0,
    name: 'Dashboard',
    numMemAssigned: 2,
    MemAssigned: ['Anweshan Bor', 'Abs Bor'],
    description: 'skfjvbvwk wouvw wuruh wroiveawofuvh efsoushf vwofuvh wofufhv ewfovue ',
    priority: 'High',
    deadline: '2/2/2020',
  },
  {
    id: 1,
    name: 'IIC',
    numMemAssigned: 0,
    MemAssigned: ['abs', 'csd'],
    description: 'skfjvbvwk wouvw wuruh wroiveawofuvh efsoushf vwofuvh wofufhv ewfovue ',
    priority: 'High',
    deadline: '2/2/2020',
  },
  {
    id: 2,
    name: 'Yeet Saber',
    numMemAssigned: 0,
    MemAssigned: ['ert', 'qwerty'],
    description: 'skfjvbvwk wouvw wuruh wroiveawofuvh efsoushf vwofuvh wofufhv ewfovue ',
    priority: 'High',
    deadline: '2/2/2020',
  },
  {
    id: 3,
    name: 'Portfolio',
    numMemAssigned: 3,
    MemAssigned: ['EDVar', 'csadvsargd', 'srfbvsf'],
    description: 'skfjvbvwk wouvw wuruh wroiveawofuvh efsoushf vwofuvh wofufhv ewfovue ',
    priority: 'High',
    deadline: '2/2/2020',
  },
  {
    id: 4,
    name: 'CAIC',
    numMemAssigned: 2,
    MemAssigned: ['safva', 'sfbs'],
    description: 'skfjvbvwk wouvw wuruh wroiveawofuvh efsoushf vwofuvh wofufhv ewfovue ',
    priority: 'High',
    deadline: '2/2/2020',
  },
];
