// eslint-disable-next-line import/prefer-default-export
const dumUsers = [
    {
        id: 0,
        email: 'anweshanbor@gmail.com',
        name: 'Anweshan Bor',
        password: '12345678',
        entry_no: '2018EE30878',
        hostel: 'KUMAON',
        gender: 'male',
        join_year: new Date('23/07/2018'),
        grad_year: new Date('23/07/2018'),
        birth_date: new Date('23/07/2018'),
        mobile_number: '9582575393',
        hometown: 'Bishnupur, West Bengal',
        interests:
            'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
        specialization: 'Python, C++, Java, Frontend Webdev',
        intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
        category: 'frontend',
        display_on_website: true,
        url: new Map([
            ['linkedIn', 'www.linkedin.com/anweshanbor'],
            ['google', 'wwww.google.com'],
            ['facebook', 'wwww.facebook.com'],
        ]),
        created_by: null,
        updated_by: null,
        privelege_level: 'Admin',
    },
    {
        id: 1,
        email: 'anweshanbor@gmail.com',
        name: 'ABC Bor',
        password: '12345678',
        entry_no: '2018EE30878',
        hostel: 'KUMAON',
        gender: 'male',
        join_year: new Date('23/07/2018'),
        grad_year: new Date('23/07/2018'),
        birth_date: new Date('23/07/2018'),
        mobile_number: '9582575393',
        hometown: 'Bishnupur, West Bengal',
        interests:
            'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
        specialization: 'Python, C++, Java, Frontend Webdev',
        intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
        category: 'frontend',
        display_on_website: false,
        url: new Map([
            ['linkedIn', 'www.linkedin.com/anweshanbor'],
            ['google', 'wwww.google.com'],
            ['facebook', 'wwww.facebook.com'],
        ]),
        created_by: null,
        updated_by: null,
        privelege_level: 'Unapproved_User',
    },
    {
        id: 2,
        email: 'anweshanbor@gmail.com',
        name: 'DEF Bor',
        password: '12345678',
        entry_no: '2018EE30878',
        hostel: 'KUMAON',
        gender: 'male',
        join_year: new Date('23/07/2018'),
        grad_year: new Date('23/07/2018'),
        birth_date: new Date('23/07/2018'),
        mobile_number: '9582575393',
        hometown: 'Bishnupur, West Bengal',
        interests:
            'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
        specialization: 'Python, C++, Java, Frontend Webdev',
        intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
        category: 'frontend',
        display_on_website: true,
        url: new Map([
            ['linkedIn', 'www.linkedin.com/anweshanbor'],
            ['google', 'wwww.google.com'],
            ['facebook', 'wwww.facebook.com'],
        ]),
        created_by: null,
        updated_by: null,
        privelege_level: 'Approved_User',
    },
    {
        id: 3,
        email: 'anweshanbor@gmail.com',
        name: 'GHI Bor',
        password: '12345678',
        entry_no: '2018EE30878',
        hostel: 'KUMAON',
        gender: 'male',
        join_year: new Date('23/07/2018'),
        grad_year: new Date('23/07/2018'),
        birth_date: new Date('23/07/2018'),
        mobile_number: '9582575393',
        hometown: 'Bishnupur, West Bengal',
        interests:
            'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
        specialization: 'Python, C++, Java, Frontend Webdev',
        intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
        category: 'frontend',
        display_on_website: false,
        url: new Map([
            ['linkedIn', 'www.linkedin.com/anweshanbor'],
            ['google', 'wwww.google.com'],
            ['facebook', 'wwww.facebook.com'],
        ]),
        created_by: null,
        updated_by: null,
        privelege_level: 'Approved_User',
    },
    {
        id: 4,
        email: 'anweshanbor@gmail.com',
        name: 'JKL Bor',
        password: '12345678',
        entry_no: '2018EE30878',
        hostel: 'KUMAON',
        gender: 'male',
        join_year: new Date('23/07/2018'),
        grad_year: new Date('23/07/2018'),
        birth_date: new Date('23/07/2018'),
        mobile_number: '9582575393',
        hometown: 'Bishnupur, West Bengal',
        interests:
            'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
        specialization: 'Python, C++, Java, Frontend Webdev',
        intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
        category: 'frontend',
        display_on_website: true,
        url: new Map([
            ['linkedIn', 'www.linkedin.com/anweshanbor'],
            ['google', 'wwww.google.com'],
            ['facebook', 'wwww.facebook.com'],
        ]),
        created_by: null,
        updated_by: null,
        privelege_level: 'Unapproved_User',
    },
    {
        id: 5,
        email: 'anweshanbor@gmail.com',
        name: 'MNO Bor',
        password: '12345678',
        entry_no: '2018EE30878',
        hostel: 'KUMAON',
        gender: 'male',
        join_year: new Date('23/07/2018'),
        grad_year: new Date('23/07/2018'),
        birth_date: new Date('23/07/2018'),
        mobile_number: '9582575393',
        hometown: 'Bishnupur, West Bengal',
        interests:
            'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
        specialization: 'Python, C++, Java, Frontend Webdev',
        intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
        category: 'frontend',
        display_on_website: false,
        url: new Map([
            ['linkedIn', 'www.linkedin.com/anweshanbor'],
            ['google', 'wwww.google.com'],
            ['facebook', 'wwww.facebook.com'],
        ]),
        created_by: null,
        updated_by: null,
        privelege_level: 'Approved_User',
    },
];

export default dumUsers;
