// eslint-disable-next-line import/prefer-default-export
export const dumUsers = [
  {
    id: 0,
    email: 'anweshanbor@gmail.com',
    name: 'Anweshan Bor',
    password: '12345678',
    entry_no: '2018EE30878',
    hostel: 'KUMAON',
    gender: 'male',
    join_year: '23/07/2018',
    grad_year: '20/05/2022',
    birth_date: '17/06/1999',
    mobile_number: '9582575393',
    hometown: 'Bishnupur, West Bengal',
    interests: 'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
    specialization: 'Python, C++, Java, Frontend Webdev',
    intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
    category: 'frontend',
    display_on_website: true,
    url: 'www.linkedin.com/anweshanbor',
    created_by: null,
    updated_by: null,
    privelege_level: 'Approved_User',
  },
  {
    id: 1,
    email: 'anweshanbor@gmail.com',
    name: 'ABC Bor',
    password: '12345678',
    entry_no: '2018EE30878',
    hostel: 'KUMAON',
    gender: 'male',
    join_year: '23/07/2018',
    grad_year: '20/05/2022',
    birth_date: '17/06/1999',
    mobile_number: '9582575393',
    hometown: 'Bishnupur, West Bengal',
    interests: 'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
    specialization: 'Python, C++, Java, Frontend Webdev',
    intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
    category: 'frontend',
    display_on_website: true,
    url: 'www.linkedin.com/anweshanbor',
    created_by: null,
    updated_by: null,
    privelege_level: 'Approved_User',
  },
  {
    id: 2,
    email: 'anweshanbor@gmail.com',
    name: 'DEF Bor',
    password: '12345678',
    entry_no: '2018EE30878',
    hostel: 'KUMAON',
    gender: 'male',
    join_year: '23/07/2018',
    grad_year: '20/05/2022',
    birth_date: '17/06/1999',
    mobile_number: '9582575393',
    hometown: 'Bishnupur, West Bengal',
    interests: 'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
    specialization: 'Python, C++, Java, Frontend Webdev',
    intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
    category: 'frontend',
    display_on_website: true,
    url: 'www.linkedin.com/anweshanbor',
    created_by: null,
    updated_by: null,
    privelege_level: 'Approved_User',
  },
  {
    id: 3,
    email: 'anweshanbor@gmail.com',
    name: 'GHI Bor',
    password: '12345678',
    entry_no: '2018EE30878',
    hostel: 'KUMAON',
    gender: 'male',
    join_year: '23/07/2018',
    grad_year: '20/05/2022',
    birth_date: '17/06/1999',
    mobile_number: '9582575393',
    hometown: 'Bishnupur, West Bengal',
    interests: 'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
    specialization: 'Python, C++, Java, Frontend Webdev',
    intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
    category: 'frontend',
    display_on_website: true,
    url: 'www.linkedin.com/anweshanbor',
    created_by: null,
    updated_by: null,
    privelege_level: 'Approved_User',
  },
  {
    id: 4,
    email: 'anweshanbor@gmail.com',
    name: 'JKL Bor',
    password: '12345678',
    entry_no: '2018EE30878',
    hostel: 'KUMAON',
    gender: 'male',
    join_year: '23/07/2018',
    grad_year: '20/05/2022',
    birth_date: '17/06/1999',
    mobile_number: '9582575393',
    hometown: 'Bishnupur, West Bengal',
    interests: 'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
    specialization: 'Python, C++, Java, Frontend Webdev',
    intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
    category: 'frontend',
    display_on_website: true,
    url: 'www.linkedin.com/anweshanbor',
    created_by: null,
    updated_by: null,
    privelege_level: 'Approved_User',
  },
  {
    id: 5,
    email: 'anweshanbor@gmail.com',
    name: 'MNO Bor',
    password: '12345678',
    entry_no: '2018EE30878',
    hostel: 'KUMAON',
    gender: 'male',
    join_year: '23/07/2018',
    grad_year: '20/05/2022',
    birth_date: '17/06/1999',
    mobile_number: '9582575393',
    hometown: 'Bishnupur, West Bengal',
    interests: 'Arduino, Machine Learning, RaspberryPi, Python, WebDev, Signal Processing',
    specialization: 'Python, C++, Java, Frontend Webdev',
    intro: 'My name is Anweshan Bor. My name is Anweshan Bor. My name is Anweshan Bor',
    category: 'frontend',
    display_on_website: true,
    url: 'www.linkedin.com/anweshanbor',
    created_by: null,
    updated_by: null,
    privelege_level: 'Approved_User',
  },
];
