name: Docker Compose CI

on:
  [push,pull_request]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Create environment file
        run: touch .env; echo PORT=3000 > .env
      - name: Build the Docker Compose images
        run: docker-compose build